# BorderlessMC Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=5
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-download=true

mod.id=borderlessmc
mod.name=BorderlessMC
mod.description=Allows you to play Minecraft in a borderless fullscreen window.
mod.author=ValiantGiant985
mod.license=PolyForm Shield 1.0.0
mod.sources=https://github.com/ValiantGiant985/BorderlessMC
