modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "${issues}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = '''
${description}
'''
authors = "${author}"
logoFile = "icon.png"
iconFile = "icon.png"
bannerFile = "icon.png"
displayURL = "${homepage}"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "cloth_config"
type = "optional"
[dependencies.${id}.mc-publish]
modrinth = "9s6osm5g"
curseforge = 348521

[[dependencies.${id}]]
modId = "yet_another_config_lib_v3"
type = "optional"
[dependencies.${id}.mc-publish]
modrinth = "1eAoo2KR"
curseforge = 667299

[[dependencies.${id}]]
modId = "borderlessmining"
type = "incompatible"
reason = "You already have a mod that provides borderless fullscreen. Please uninstall \"borderlessmining\"."
[dependencies.${id}.mc-publish]
modrinth = "KxYAzYLi"
curseforge = 1487420

[[dependencies.${id}]]
modId = "borderlesswindow"
type = "incompatible"
reason = "You already have a mod that provides borderless fullscreen. Please uninstall \"borderlesswindow\"."
[dependencies.${id}.mc-publish]
modrinth = "CnalMsa0"
curseforge = 378979

[[dependencies.${id}]]
modId = "concentration"
type = "incompatible"
reason = "You already have a mod that provides borderless fullscreen. Please uninstall \"concentration\"."
[dependencies.${id}.mc-publish]
modrinth = "QyvWSZ5S"
curseforge = 1120678

[[mixins]]
config = "${id}.mixins.json"

[mc-publish]
modrinth = "${modrinth}"
curseforge = "${curseforge}"
